### ISSUE TITLE
Create unique, linkable URL for search results

### ISSUE THREAD

**Issue by alanorth** [ilri/OpenRXV#13]
We could perhaps use a "share" icon? This will help us link the results in other web platforms, for example on social media, blog posts, or ILRI website author’s profile page.

Include link in exports.

**Comment by moayadnajd** [comment]
@alanorth please review

**Comment by alanorth** [comment]
Works. Thanks!

![Screenshot_2020-07-23 OpenRXV(13)-fs8](https://user-images.githubusercontent.com/191754/88257905-84fdb880-ccc7-11ea-9683-ee4388133488.png)
