### ISSUE TITLE
Public demo instance of vanilla OpenRXV with Dublin Core fields

### ISSUE THREAD

**Issue by alanorth** [ilri/OpenRXV#14]
We want to have a public instance of OpenRXV to demo the platform. It should be harvesting either demo.dspace.org or some CGSpace communities that only use Dublin Core fields so that we can highlight the "out of box" experience of OpenRXV. It would be available on: cgspace.cgiar.org/openrxv

**Comment by moayadnajd** [comment]
@alanorth please review [demo.openrxv.org](http://demo.openrxv.org)

**Comment by alanorth** [comment]
Looks great. Thanks.
