### ISSUE TITLE
Add ability to filter by month

### ISSUE THREAD

**Issue by alanorth** [ilri/OpenRXV#16]
Ability to add month to date filter? We get many request for reports of outputs in a given range of YYYY-MM to YYYY-MM.

**Comment by moayadnajd** [comment]
@alanorth Please review

**Comment by alanorth** [comment]
You can now select arbitrary date ranges in the search filters sidebar. Works well.

![Screenshot_2020-07-23 OpenRXV(12)-fs8](https://user-images.githubusercontent.com/191754/88257580-baee6d00-ccc6-11ea-8ca3-0705b14d349a.png)

Thanks!
