### ISSUE TITLE
Limit terms in subjects word cloud to top 25

### ISSUE THREAD

**Issue by alanorth** [ilri/OpenRXV#17]
Otherwise the graphic becomes unreadable, especially if there is a single dominant term. Currently on AReS there are forty-seven terms.

![chart-fs8](https://user-images.githubusercontent.com/191754/69735285-25034200-1139-11ea-8c6b-2b99d5706712.png)

**Comment by moayadnajd** [comment]
@alanorth please review

**Comment by alanorth** [comment]
The number of terms in the word cloud is configurable in the admin dashboard.

![Screenshot_2020-07-23 OpenRXV(11)-fs8](https://user-images.githubusercontent.com/191754/88257477-79f65880-ccc6-11ea-94f5-99160b638f01.png)
