### ISSUE TITLE
Add option to select collections in search filters

### ISSUE THREAD

**Issue by alanorth** [ilri/OpenRXV#20]
Some users have expressed interest in being able to select collections in the search filters. I know that there are limitations in the DSpace REST API, so we should discuss if this is possible.

**Comment by moayadnajd** [comment]
@alanorth please check

**Comment by alanorth** [comment]
Works well.

![Screenshot_2020-07-23 OpenRXV(7)-fs8](https://user-images.githubusercontent.com/191754/88256951-49fa8580-ccc5-11ea-8692-91d696b8a876.png)
