### ISSUE TITLE
Add "usage rights" (license) and "series" to search filters

### ISSUE THREAD

**Issue by alanorth** [ilri/OpenRXV#21]
It is very useful to be able to filter by license and series. Users often use these fields when making reports at the end of the year.

In most DSpace repositories the fields are probably:
- `dc.rights`
- `dc.relation.ispartofseries`

In CG Core v2 the fields will be:
- `dcterms.license`
- `dcterms.isPartOf`

Perhaps we need to use one configuration in OpenRXV, and override it in AReS.

**Comment by moayadnajd** [comment]
@alanorth please review

**Comment by alanorth** [comment]
Done. Thanks.
![Screenshot_2020-07-23 OpenRXV(6)-fs8](https://user-images.githubusercontent.com/191754/88256857-01db6300-ccc5-11ea-8327-aa0701015822.png)
