### ISSUE TITLE
Allow configuration of Google Analytics

### ISSUE THREAD

**Issue by alanorth** [ilri/OpenRXV#22]
It should be possible for the user to configure their Google Analytics API key in the application configuration. We need to be careful about GDPR, though. Only enable Google Analytics if the user accepts the cookie.

**Comment by moayadnajd** [comment]
@alanorth please review

**Comment by alanorth** [comment]
Analytics code is configurable in the admin dashboard.

![Screenshot_2020-07-23 OpenRXV(5)-fs8](https://user-images.githubusercontent.com/191754/88256732-b32dc900-ccc4-11ea-9b05-783e2338db11.png)
