### ISSUE TITLE
Move "refresh" icon into search sidebar

### ISSUE THREAD

**Issue by alanorth** [ilri/OpenRXV#23]
The "refresh" icon should be in the sidebar because it related to search and only applies when the user has customized the search settings. Also, as this is for clearing or cleaning the current search settings, this might be more clear if it was a different icon—perhaps a [broom](https://en.wikipedia.org/wiki/File:Edit-clear.svg) or an eraser?

**Comment by moayadnajd** [comment]
@alanorth please review

**Comment by alanorth** [comment]
Done. Thanks!

![Screenshot_2020-07-23 OpenRXV(4)-fs8](https://user-images.githubusercontent.com/191754/88256572-5af6c700-ccc4-11ea-9c6b-36d57199b87c.png)
