### ISSUE TITLE
Erroneous values in Excel export

### ISSUE THREAD

**Issue by alanorth** [ilri/OpenRXV#25]
Some fields have errors in the Excel export, for example:

- Authors, Affiliations, Languages, and Countries are "None"
- CRPs have some values like `=grain legumes`
- Regions are mostly blank, but sometimes contain values like "A", when the item should have "AFRICA" etc

Attaching example XLSX generated on 2019-11-28.

[AReS-1-1dc945df-65d0-44b9-b587-836ea0ab08f6.xlsx](https://github.com/ilri/OpenRXV/files/3901193/AReS-1-1dc945df-65d0-44b9-b587-836ea0ab08f6.xlsx)

**Comment by moayadnajd** [comment]
@alanorth Please check changes

**Comment by alanorth** [comment]
Looking better, @moayadnajd. I still see some errors in CRPs and Regions, though. See attached XLSX. Search terms were all items by author "Orth, Alan".

[AReS-1-8f618850-9afa-40b6-945a-6903a125a788.xlsx](https://github.com/ilri/OpenRXV/files/4063599/AReS-1-8f618850-9afa-40b6-945a-6903a125a788.xlsx)

**Comment by moayadnajd** [comment]
@alanorth Please check now
