### ISSUE TITLE
Re-work the "Info Products Overview" (world map)

### ISSUE THREAD

**Issue by alanorth** [ilri/OpenRXV#26]
Change the title to "Info Products Geographic Focus" and allow switching between different visualization formats:

- Map
- Word cloud based on country names
- Table

Optionally, if countries can be grouped by region, then can use a [packed bubble chart](https://www.highcharts.com/demo/packed-bubble) with the color of the circle for the region, label for country, and size of bubble for number of products.

**Comment by moayadnajd** [comment]
@alanorth please review

**Comment by alanorth** [comment]
Yes the text has been updated and other chart types are available. Thanks.

![Screenshot_2020-07-23 OpenRXV(14)-fs8](https://user-images.githubusercontent.com/191754/88258203-487e8c80-ccc8-11ea-9868-6f199ffce70a.png)
