### ISSUE TITLE
Re-work the contributors, affiliations, CRPs, and funders blocks

### ISSUE THREAD

**Issue by alanorth** [ilri/OpenRXV#27]
Rename block headings:

- Top Contributors→Authors
- Top Affiliations→Author Affiliations

Allow other types of graphic visualizations:

- List (default)
- Network
- Word cloud

---
*Note: CRPs won't exist in the OpenRXV version, so perhaps we need a separate issue to track that in AReS.*

**Comment by moayadnajd** [comment]
@alanorth please review

**Comment by alanorth** [comment]
Done. Thanks!
![Screenshot_2020-07-23 OpenRXV(3)-fs8](https://user-images.githubusercontent.com/191754/88256514-2be05580-ccc4-11ea-9037-5c6598ee971a.png)
