### ISSUE TITLE
Add total views/downloads for current search result to top section

### ISSUE THREAD

**Issue by alanorth** [ilri/OpenRXV#28]
If possible we would like to see the cumulative number of views/downloads for the current search results. Maybe at the top near the total number of authors etc?

![Screenshot_2019-12-11 AReS-fs8](https://user-images.githubusercontent.com/191754/70632758-2142e580-1c38-11ea-803a-4c10f565d956.png)

Tooltip text should be "Total views and downloads of items matching the query".

**Comment by moayadnajd** [comment]
@alanorth please review

**Comment by alanorth** [comment]
View and downloads available at the top of the explorer. Thanks!


![Screenshot_2020-07-23 OpenRXV(2)-fs8](https://user-images.githubusercontent.com/191754/88256362-d2782680-ccc3-11ea-9bf0-ab2f8e99cb39.png)
