### ISSUE TITLE
Adjust options for sorting information products

### ISSUE THREAD

**Issue by alanorth** [ilri/OpenRXV#31]
OpenRXV currently sorts information products by "issue date". It would be nice to be able to sort by "accession date" (dc.date.accessioned).

![Screenshot_2019-12-23 AReS-fs8](https://user-images.githubusercontent.com/191754/71355004-58918a80-2586-11ea-98b2-8ebfbcb5b1f4.png)

Also, update the text of the drop-down menu to be more clear to non-technical users:

- Date of publication
- Date added to repository
- Type of output
- First author
- Altmetric attention score
- Repository views & downloads

**Comment by moayadnajd** [comment]
@alanorth  please review

**Comment by alanorth** [comment]
I see the sort options available now. Thank you. It seems that a few are not working:

- Date added to repository
- Type of output
- First author (though actually I don't know if this is even feasible due to mixing of author name formats)

**Comment by alanorth** [comment]
Working great. Thanks!

![Screenshot_2020-07-23 OpenRXV-fs8](https://user-images.githubusercontent.com/191754/88256193-3d752d80-ccc3-11ea-90a9-4f2dd503102a.png)
