### ISSUE TITLE
Add matching dashboard as was available in version 1

### ISSUE THREAD

**Issue by enricobonaiuti** [ilri/OpenRXV#32]

**Comment by moayadnajd** [comment]
@enricobonaiuti 
this needs 
- login page username and password 
- admin area with two section 
1- mapping values eg ( en -> english) 
2- mapping metadata ( dc.type => cg.type )

**Comment by alanorth** [comment]
Can we also please prefer the CGSpace style of metadata values for contributors, affiliations, CRPs, and sponsors? I see the MEL values with acronyms are currently preferred, for example:

- International Livestock Research Institute - ILRI
- International Center for Agricultural Research in the Dry Areas - ICARDA
- United States Agency for International Development - USAID
- CRP on Fish Agri-Food Systems - FISH

The acronyms are ugly. Thanks.

![ares-contributors-affiliations-fs8](https://user-images.githubusercontent.com/191754/72894360-cbc42300-3d23-11ea-9b9a-07bea8eb9933.png)
![ares-crps-funders-fs8](https://user-images.githubusercontent.com/191754/72894361-cbc42300-3d23-11ea-9379-bd4b255263a5.png)

**Comment by enricobonaiuti** [comment]
@alanorth sure. @moayadnajd can we ensure we harmonize MELSPACE as well?

**Comment by moayadnajd** [comment]
@alanorth please review

**Comment by alanorth** [comment]
Mapping dashboard works, though we need to import or swap the clean mappings with no acronyms.

![Screenshot_2020-07-23 OpenRXV(15)-fs8](https://user-images.githubusercontent.com/191754/88259572-3fdb8580-cccb-11ea-83fe-c106aecabef6.png)
