### ISSUE TITLE
Update text in labels and tooltips in cards/blocks

### ISSUE THREAD

**Issue by alanorth** [ilri/OpenRXV#33]
Update text in labels and tooltips for the following blocks in the _first row_:

- **Total items**:
  - _Tooltip_: Total items matching the query
- **Open Access**:
  - _Label_: XXX / % Openly accessible
  - _Tooltip_: Number of items free to view
- **Limited Access**:
  - _Label_: XXX / % Restricted access
  - _Tooltip_: Number of items not free to view
- **Languages**: Remove this block
- **Authors**:
  - _Tooltip_: Number of unique authors of items matching the query
- **Author Institutions**:
  - _Tooltip_: Number of unique author institutions of items matching the query
- **CRPs & Platforms**: Remove this block
- **Countries**:
  - _Tooltip:_ Number of countries items in the query cover

Update text in labels and tooltips for the following blocks in the _second row_:

- **Items by type**:
  - _Tooltip_: This chart shows the types of information products matching the query. Click on an item type in the legend to include/exclude it from the chart. Click the export icon for download options.
- **Items by subject focus**:
  - _Tooltip_: This chart shows the top subject terms assigned to the information products matching the query. Click on a term to see its frequency. Click the export icon for download options.

Update text in labels and tooltips for the following blocks in the _third row_:

- **Map**:
  - _Tooltip_: This map shows the country distribution of information products matching the query. It is based on countries assigned to an item and indicates that an item is about a country. Darker shading indicates more items. Click on a country to see the number of items about that country.  Click the export icon for download options.
  - _When country clicked_: change "publications" to "information products"

Update text in labels and tooltips for the following blocks in the _fourth row_:

- **Information product analysis**:
  - _Label_: Change "Categories" and "Columns" to "Information product types" and "Year ranges"
  - _Tooltip_: Select combinations of item types and years to generate a chart over time. Click the export icon for download options.

Update text in labels and tooltips for the following blocks in the _fifth row_:

- **Authors**:
  - _Tooltip_: This table shows the most frequent authors for information products matching the query. Click the export icon for download options.
- **Institutions**:
  - _Tooltip_: This table shows the most frequent author affiliations for information products matching the query. Click the export icon for download options.

Update text in labels and tooltips for the following blocks in the _sixth row_:

- **CRPs and Platforms**:
  - _Tooltip_: This table shows the most frequent CGIAR programs or platforms associated with information products matching the query. Click the export icon for download options.
- **Funders and investors**:
  - _Tooltip_: This table shows the most frequent funders, sponsors or investors associated with information products matching the query. Click the export icon for download options.

Update text in labels and tooltips for the following blocks in the _seventh row_:

- **Information Products**:
  - _Tooltip_: This table lists all items matching the query. Choose from the different sort options. Click the export icon for download options.

**Comment by moayadnajd** [comment]
@alanorth please review

**Comment by alanorth** [comment]
Text updated from the AReS dashboard. Looks good now. Thanks!
