### ISSUE TITLE
Minor adjustments to the Information Products Analysis

### ISSUE THREAD

**Issue by alanorth** [ilri/OpenRXV#37]
In the old AReS we could select years *and* types:

![Screenshot_2020-06-25 AReS-fs8](https://user-images.githubusercontent.com/191754/85681771-4b3f8f00-b6d4-11ea-94ea-1dcebf043c78.png)

In the new one we can only select years:

![Screenshot_2020-06-25 OpenRXV-fs8](https://user-images.githubusercontent.com/191754/85681801-54306080-b6d4-11ea-9fca-995aa80bc5db.png)

Also, can we adjust the text on the Y axis to say "Information Products" instead of "Publications"?

**Comment by moayadnajd** [comment]
@alanorth i changed the text since now you can change X and Y access from the admin area there no need to change it from here also change it from here it will confuse the user since it will not reflect the main query

**Comment by alanorth** [comment]
This is working and we discussed the possibilities of this section in yesterday's meeting. Users are happy with how this works currently and we will pursue minor usability updates soon.
