### ISSUE TITLE
"Reset" filters doesn't reset all filters

### ISSUE THREAD

**Issue by alanorth** [ilri/OpenRXV#39]
The general search text doesn't get cleared when you use "Reset Filters".

![Screenshot_2020-09-02 OpenRXV(1)-fs8](https://user-images.githubusercontent.com/191754/91963333-6652fe80-ed16-11ea-898f-c477f1a7d911.png)

**Comment by alanorth** [comment]
Partially fixed in #71. Now I notice that the year slider doesn't get reset.

**Comment by ShacMiester** [comment]
Solved! :hammer:
