### ISSUE TITLE
Error building api container with NodeJS 15

### ISSUE THREAD

**Issue by alanorth** [ilri/OpenRXV#46]
Error in the `api` container during `docker-compose up -d`:

```
> api@0.0.1 install_and_run
> npm i && cp example.env .env &&  npm run copy:assets && npm run build && npm run start:prod

glob error [Error: EACCES: permission denied, scandir '/root/.npm/_logs'] {
  errno: -13,
  code: 'EACCES',
  syscall: 'scandir',
  path: '/root/.npm/_logs'
}

up to date in 7s
cp: cannot create regular file '.env': Permission denied
npm notice
npm notice New patch version of npm available! 7.0.3 -> 7.0.7
npm notice Changelog: <https://github.com/npm/cli/releases/tag/v7.0.7>
npm notice Run `npm install -g npm@7.0.7` to update!
npm notice
npm ERR! code 1
npm ERR! path /backend
npm ERR! command failed
npm ERR! command sh -c npm i && cp example.env .env &&  npm run copy:assets && npm run build && npm run start:prod

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-10-31T14_52_49_249Z-debug.log
```

The container keeps restarting over and over. I suspect we need to pin the `node` container version rather than using the latest one. The production [OpenRXV instance on AReS](https://cgspace.cgiar.org/explorer) is using NodeJS 11, but the current node image on Docker hub is 15.

**Comment by sagar2009kumar** [comment]
Please select the correct version of nodejs in the container on which you have built the project.

**Comment by alanorth** [comment]
@sagar2009kumar yes we did that in ce70aa1321e1e9da654a7a561792542e1361b766. It's working now, pinned to NodeJS 12. Are you using OpenRXV?

**Comment by sagar2009kumar** [comment]
> @sagar2009kumar yes we did that in ce70aa1321e1e9da654a7a561792542e1361b766. It's working now, pinned to NodeJS 12. Are you using OpenRXV?

No @alanorth Actually I was working on a Nodejs project. Then changing the version solve this issue. That's why I think it would be useful if u are also stuck in the issue. 😬
