### ISSUE TITLE
Country formatter handles names with spaces incorrectly

### ISSUE THREAD

**Issue by alanorth** [ilri/OpenRXV#50]
The country formatter addon in `backend/src/harvester/consumers/fetch.consumer.ts` handles names with spaces incorrectly, which causes part of the name to be lower case:

- Burkina faso
- Puerto rico
- United kingdom
- Timor-leste

Also, I think country names with commas are not handled properly...?

**Comment by ShacMiester** [comment]
Solved! :hammer:

**Comment by alanorth** [comment]
OK I don't have a way to test this without doing a full re-harvest in AReS (which takes 10 hours and is kinda a pain in the ass), so I'm just going to assume you've tested this?
