### ISSUE TITLE
Year slider is buggy

### ISSUE THREAD

**Issue by alanorth** [ilri/OpenRXV#51]
The year slider has some buggy behavior that I can't quite figure out:

- Clear the search filters
- Set the year slider to 2013–2021
- Select author "Duncan, Alan J."
- Year slider changes to 2004–2020

![Screenshot_2020-11-18 OpenRXV-fs8](https://user-images.githubusercontent.com/191754/99522366-383c9c80-299e-11eb-80cb-1e198d7b3d32.png)

Furthermore, with this query I see 141 information products, but 224 openly accessible:

![Screenshot_2020-11-18 OpenRXV(1)-fs8](https://user-images.githubusercontent.com/191754/99522440-530f1100-299e-11eb-8117-8cf523a8729f.png)

**Comment by ShacMiester** [comment]
Solved! :hammer:

**Comment by alanorth** [comment]
> Solved! :hammer:

w00t! Even the issue with the incorrect total / open access count?

**Comment by ShacMiester** [comment]
@alanorth Not really, i think this issue is related to another one #64, we'll have to fix that first..and sorry, forgot about the second part of this issue!

**Comment by alanorth** [comment]
I guess we can close this issue since the year slider bug is fixed. I also mentioned the incorrect counters in https://github.com/ilri/OpenRXV/issues/66, perhaps we should solve that there. I don't think it's related to the duplicate items in #64 (that's some issue with replacing the Elasticsearch index during re-harvest).
