### ISSUE TITLE
Item appears twice in OpenRXV

### ISSUE THREAD

**Issue by alanorth** [ilri/OpenRXV#67]
From time to time I see items that appear twice in AReS. In this case, if you filter by handle 10568/66839 you will see it twice:

![Screenshot_2021-01-04 OpenRXV-fs8](https://user-images.githubusercontent.com/191754/103518000-b2a47b80-4e7b-11eb-94ae-1391ac8b58a0.png)

"2" information products:

![Screenshot_2021-01-04 OpenRXV(1)-fs8](https://user-images.githubusercontent.com/191754/103518037-c05a0100-4e7b-11eb-9bf7-b09ab3d23c84.png)

And duplicated in the list of information products:

![Screenshot_2021-01-04 OpenRXV(2)-fs8](https://user-images.githubusercontent.com/191754/103518061-c8b23c00-4e7b-11eb-9f52-0be1be1d3b68.png)

**Comment by moayadnajd** [comment]
@alanorth seems this issue is not appearing any more

**Comment by alanorth** [comment]
Yes this particular item is no longer duplicated. It *might* have been related to the [issue with DSpace 5/6 REST API where items are not returned in a deterministic order](https://jira.lyrasis.org/browse/DS-3849). I patched that last month. I will re-open this issue if I see it again.

**Comment by alanorth** [comment]
Hello! We found more duplicates. See this shared link:

https://cgspace.cgiar.org/explorer/shared/heEOz3YBnXdK69bR2ra6

See attached on the first page of results:

![Screenshot_2021-02-01 OpenRXV](https://user-images.githubusercontent.com/191754/106447116-c696c980-6489-11eb-974d-5befa299556f.png)

Item [10568/110932](https://hdl.handle.net/10568/110932) appears twice. Also, if you export those results you will see more. I think we need to check if a handle exists before inserting it during harvesting.

**Comment by alanorth** [comment]
Getting a lot of reports from users (not good!!!) that they are seeing duplicate items in search results and reports. See attached where one item appears twice, and only one of them has the Altmetric donut!

![image005](https://user-images.githubusercontent.com/191754/110360133-029fea00-8047-11eb-97c4-af0564b7bdd3.jpg)

@moayadnajd we need to look at this seriously very soon. Users are going to have bad experiences burned into their brains and it is critical that we keep them trusting and using AReS!

**Comment by alanorth** [comment]
After talking to @moayadnajd on this we realize that this duplicate items issue and the missing items issue (#62) are probably caused by the long harvesting time, as the time between harvesting page 0 and page 900 on CGSpace can take about ten hours, and during that time more items get added and the pages can shift.

We decided that, in addition to the current heavy "full" harvest of `/rest/items`, we need to add a "quick" or "update" harvest that checks DSpace's XML sitemap to get a list of all items in the repository and compare it with those in the Elasticsearch index. Any missing items can be harvested one by one using the item's ID/UUID via `/rest/items/{uuid}`, or using the item's handle via `/rest/handle/10568/16707`.

The benefit of this approach is that it can be faster than re-harvesting the entire repository and just praying that you get the missing items, and also that the XML sitemap is already present on all DSpace repositories and is fast to generate, for example:

- https://repo.mel.cgiar.org/sitemap
- https://dspacetest.cgiar.org/sitemap

**Comment by alanorth** [comment]
After several weeks of evaluation we think this is working well. Closing.
