### ISSUE TITLE
Duplicated icons

### ISSUE THREAD

**Issue by ShacMiester** [ilri/OpenRXV#69]
![duplicatedIcons](https://user-images.githubusercontent.com/58075416/105381603-da376a00-5c17-11eb-970a-ab8cbc441ccf.png)

**Comment by alanorth** [comment]
Solved in 8bca80b6045c9776676fa07f07cb5b81e2950f77, which will fix it for new components. Edited `backend/data/explorer.json` to remove the existing duplicate components.
